[build]
  publish = "compliance_site"

# Disable Pretty URLs so /app.js is NOT rewritten to /app.js/index.html
[build.processing.html]
  pretty_urls = false

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    X-Content-Type-Options = "nosniff"
