// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbgfPFFe6GdRdEfC0b56qf5WgCtY-VXv8',
    appId: '1:591328908781:web:ddc036782df1ffd84043e4',
    messagingSenderId: '591328908781',
    projectId: 'jobmarketplaceaz',
    authDomain: 'jobmarketplaceaz.firebaseapp.com',
    storageBucket: 'jobmarketplaceaz.firebasestorage.app',
    measurementId: 'G-EGKX8DNBDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6UIsSBd5sKdHavLk8U372cdmkkw1mbog',
    appId: '1:591328908781:android:aac75d23b8ff8b4b4043e4',
    messagingSenderId: '591328908781',
    projectId: 'jobmarketplaceaz',
    storageBucket: 'jobmarketplaceaz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8VbSbjdds1zlTYnoy_-OmkKnSwvMlLUM',
    appId: '1:591328908781:ios:77b0d940c052c4934043e4',
    messagingSenderId: '591328908781',
    projectId: 'jobmarketplaceaz',
    storageBucket: 'jobmarketplaceaz.firebasestorage.app',
    iosBundleId: 'com.is.tap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8VbSbjdds1zlTYnoy_-OmkKnSwvMlLUM',
    appId: '1:591328908781:ios:4cc71be1603302a14043e4',
    messagingSenderId: '591328908781',
    projectId: 'jobmarketplaceaz',
    storageBucket: 'jobmarketplaceaz.firebasestorage.app',
    iosBundleId: 'com.example.azerbaijanJobMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbgfPFFe6GdRdEfC0b56qf5WgCtY-VXv8',
    appId: '1:591328908781:web:75b6dc8ddc2f3ea34043e4',
    messagingSenderId: '591328908781',
    projectId: 'jobmarketplaceaz',
    authDomain: 'jobmarketplaceaz.firebaseapp.com',
    storageBucket: 'jobmarketplaceaz.firebasestorage.app',
    measurementId: 'G-BYGVRTY0K0',
  );
}
